# Generated by Django 5.0 on 2025-07-28 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cottageInstance', '0002_cottageinstancemodel_delete_cottagemastermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_to_cottage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_to_cottage_accounts', to='cottageInstance.cottageinstancemodel'),
        ),
    ]
