# Generated by Django 5.0 on 2025-07-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_access_to_cottage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_color',
            field=models.CharField(default='#378006', max_length=50),
            preserve_default=False,
        ),
    ]
