# Generated by Django 5.0 on 2025-07-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_paid',
            field=models.BooleanField(default=False),
        ),
    ]
