# Generated by Django 5.0 on 2025-07-31 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_stripe_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_paid',
        ),
    ]
