# Generated by Django 5.0 on 2025-07-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_stripe_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stripe_subscription',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic')], default='free', max_length=10),
        ),
    ]
