# Generated by Django 5.0 on 2025-08-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_stripe_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stripe_subscription',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Standard', 'Standard')], default='free', max_length=10),
        ),
    ]
