# Generated by Django 5.0 on 2025-08-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_stripe_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_payment_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_subscription',
        ),
    ]
