# Generated by Django 5.0 on 2025-08-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_color',
            field=models.CharField(default='#3C86FE', max_length=50),
        ),
    ]
