# Generated by Django 5.0 on 2025-07-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0003_reservation_reservationowner'),
        ('tasks', '0003_task_responsible_for_the_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='linked_to_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendarApp.reservation'),
        ),
    ]
