# Generated by Django 5.0 on 2025-07-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0004_alter_reservation_reservationowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='ReservationOwner',
            new_name='reservationOwner',
        ),
    ]
