# Generated by Django 5.2.2 on 2025-06-09 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('pressure', 'Pressure'), ('light', 'Light'), ('motion', 'Motion'), ('air_quality', 'Air Quality')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=10)),
                ('unit', models.CharField(max_length=20)),
                ('last_reading', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold'), ('offline', 'Offline'), ('anomaly', 'Anomaly')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['owner', 'status'], name='sensors_sen_owner_i_c3f00a_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['type'], name='sensors_sen_type_8c3416_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['created_at'], name='sensors_sen_created_2382ef_idx'),
        ),
        migrations.AddIndex(
            model_name='sensoralert',
            index=models.Index(fields=['sensor', 'is_resolved'], name='sensors_sen_sensor__50d704_idx'),
        ),
        migrations.AddIndex(
            model_name='sensoralert',
            index=models.Index(fields=['severity', 'is_resolved'], name='sensors_sen_severit_19bf65_idx'),
        ),
        migrations.AddIndex(
            model_name='sensoralert',
            index=models.Index(fields=['created_at'], name='sensors_sen_created_22716c_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['sensor', 'timestamp'], name='sensors_sen_sensor__20c034_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['timestamp'], name='sensors_sen_timesta_a94ae6_idx'),
        ),
    ]