# Generated by Django 5.2.2 on 2025-07-27 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sensor',
            name='sensors_sen_type_8c3416_idx',
        ),
        migrations.AddField(
            model_name='sensor',
            name='code',
            field=models.CharField(default='code', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(default='sensor1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(blank=True, choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('pressure', 'Pressure'), ('light', 'Light'), ('motion', 'Motion'), ('air_quality', 'Air Quality')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
