# Generated by Django 5.0 on 2025-07-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottageInstance', '0002_cottageinstancemodel_delete_cottagemastermodel'),
        ('sensors', '0002_remove_sensor_sensors_sen_type_8c3416_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='cottageInstance.cottageinstancemodel'),
        ),
    ]
