# Generated by Django 5.0 on 2025-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottageInstance', '0002_cottageinstancemodel_delete_cottagemastermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottageinstancemodel',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cottageinstancemodel',
            name='stripe_payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cottageinstancemodel',
            name='stripe_subscription',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard')], default='free', max_length=10),
        ),
    ]
