# Generated by Django 5.0 on 2025-08-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottageInstance', '0003_cottageinstancemodel_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottageinstancemodel',
            old_name='adress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='cottageinstancemodel',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Standard', 'Standard')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cottageinstancemodel',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cottageinstancemodel',
            name='stripe_subscription',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Standard', 'Standard')], max_length=15, null=True),
        ),
    ]
