# Generated by Django 5.0 on 2025-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottageInstance', '0004_rename_adress_cottageinstancemodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottageinstancemodel',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
