# Generated by Django 5.0 on 2025-08-06 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottageInstance', '0005_alter_cottageinstancemodel_stripe_subscription_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cottageinstancemodel',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='cottages', to=settings.AUTH_USER_MODEL),
        ),
    ]
