# Generated by Django 5.0 on 2025-08-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cottageInstance', '0006_cottageinstancemodel_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottageinstancemodel',
            old_name='accounts',
            new_name='CottageUsers',
        ),
    ]
