# Generated by Django 5.0 on 2025-07-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottageInstance', '0002_cottageinstancemodel_delete_cottagemastermodel'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cottageInstance.cottageinstancemodel'),
        ),
    ]
